"""Password hashing utilities."""

import base64
import hashlib
import hmac
import json
import secrets
import time


HASH_ALGORITHM = "pbkdf2_sha256"
HASH_ITERATIONS = 100_000


def hash_password(password: str) -> str:
    """Hash a password using PBKDF2 and a random salt."""

    salt = secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt.encode("utf-8"),
        HASH_ITERATIONS,
    )
    encoded = base64.b64encode(digest).decode("ascii")
    return f"{HASH_ALGORITHM}${HASH_ITERATIONS}${salt}${encoded}"


def verify_password(password: str, password_hash: str) -> bool:
    """Verify a password against a hash generated by hash_password."""

    try:
        algorithm, iterations_raw, salt, encoded = password_hash.split("$", 3)
        iterations = int(iterations_raw)
    except ValueError:
        return False

    if algorithm != HASH_ALGORITHM:
        return False

    digest = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt.encode("utf-8"),
        iterations,
    )
    expected = base64.b64encode(digest).decode("ascii")
    return hmac.compare_digest(expected, encoded)


def create_token(subject: str, secret: str, expires_in_seconds: int = 3600) -> str:
    """Create a signed compact token for API authentication."""

    payload = {
        "sub": subject,
        "exp": int(time.time()) + expires_in_seconds,
        "nonce": secrets.token_hex(8),
    }
    payload_raw = base64.urlsafe_b64encode(json.dumps(payload).encode("utf-8")).decode("ascii")
    signature = hmac.new(secret.encode("utf-8"), payload_raw.encode("ascii"), hashlib.sha256)
    signature_raw = base64.urlsafe_b64encode(signature.digest()).decode("ascii")
    return f"{payload_raw}.{signature_raw}"


def verify_token(token: str, secret: str) -> str | None:
    """Return token subject when the signature and expiration are valid."""

    try:
        payload_raw, signature_raw = token.split(".", 1)
        expected = hmac.new(secret.encode("utf-8"), payload_raw.encode("ascii"), hashlib.sha256)
        expected_raw = base64.urlsafe_b64encode(expected.digest()).decode("ascii")
        if not hmac.compare_digest(expected_raw, signature_raw):
            return None
        payload = json.loads(base64.urlsafe_b64decode(payload_raw.encode("ascii")))
    except (ValueError, json.JSONDecodeError):
        return None
    if int(payload.get("exp", 0)) < int(time.time()):
        return None
    return str(payload.get("sub"))
